### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by AngeloBenjamin0** [nyorem/NierAutomataTextDump#1]
Hi. When I try to run the script I get the error
```
Traceback (most recent call last):
  File "C:\Users\angel\Downloads\NierAutomataTextDump-master\scripts\organizeText.py", line 65, in <module>
    assert os.path.isfile(ALL_MISSIONS_FILE)
AssertionError
```
Is it possible to do something about it? I don't really know what it is.

**Comment by nyorem** [comment]
The script should work, maybe you didn't run it in the root directory?

You should do the following to generate the full website:
```
git clone https://github.com/nyorem/NierAutomataTextDump.git
cd NierAutomataTextDump
mkdir -p website/missions
python3 scripts/organizeText.py
```

**Comment by AngeloBenjamin0** [comment]
It's working now. I also had to replace line 228
`with open(filename, "r") as f:` to `with open(filename, "r", encoding="utf8") as f:`
and line 285 `with open(fname, "w") as f:` to `with open(fname, "w", encoding="utf8") as f:`
because I was getting an encoding error. 
Thanks.
